local config = {
    ["widow queen (mountable)"] = { mountid = 1, tamemessage = "voce conseguiu sua montaria" },
    ["racing bird (mountable)"] = { mountid = 2, tamemessage = "voce conseguiu sua montaria" },
    ["war bear (mountable)"] = { mountid = 3, tamemessage = "voce conseguiu sua montaria" },
    ["black sheep (mountable)"] = { mountid = 4, tamemessage = "voce conseguiu sua montaria" },
    ["midnight panther (mountable)"] = { mountid = 5, tamemessage = "voce conseguiu sua montaria" },
    ["draptor (mountable)"] = { mountid = 6, tamemessage = "voce conseguiu sua montaria" },
    ["titanica (mountable)"] = { mountid = 7, tamemessage = "voce conseguiu sua montaria" },
    ["tin lizzard (mountable)"] = { mountid = 8, tamemessage = "voce conseguiu sua montaria" },
    ["blazebringer (mountable)"] = { mountid = 9, tamemessage = "voce conseguiu sua montaria" },
    ["rapid boar (mountable)"] = { mountid = 10, tamemessage = "voce conseguiu sua montaria" },
    ["stampor (mountable)"] = { mountid = 11, tamemessage = "voce conseguiu sua montaria" },
    ["undead cavebear (mountable)"] = { mountid = 12, tamemessage = "voce conseguiu sua montaria" },
    ["donkey (mountable)"] = { mountid = 13, tamemessage = "voce conseguiu sua montaria" },
    ["tiger slug (mountable)"] = { mountid = 14, tamemessage = "voce conseguiu sua montaria" },
    ["uniwheel (mountable)"] = { mountid = 15, tamemessage = "voce conseguiu sua montaria" },
    ["crystal wolf (mountable)"] = { mountid = 16, tamemessage = "voce conseguiu sua montaria" },
    ["war horse (mountable)"] = { mountid = 17, tamemessage = "voce conseguiu sua montaria" },
    ["kingly deer (mountable)"] = { mountid = 18, tamemessage = "voce conseguiu sua montaria" },
    ["tamed panda (mountable)"] = { mountid = 19, tamemessage = "voce conseguiu sua montaria" },
    ["dromedary (mountable)"] = { mountid = 20, tamemessage = "voce conseguiu sua montaria" },
    ["scorpion king (mountable)"] = { mountid = 21, tamemessage = "voce conseguiu sua montaria" },
    ["rented horse (gray) (mountable)"] = { mountid = 25, tamemessage = "voce conseguiu sua montaria" },
    ["rented horse (brown) (mountable)"] = { mountid = 26, tamemessage = "voce conseguiu sua montaria" },
    ["lady bug (mountable)"] = { mountid = 27, tamemessage = "voce conseguiu sua montaria" },
    ["manta ray (mountable)"] = { mountid = 28, tamemessage = "voce conseguiu sua montaria" },
    ["ironblight (mountable)"] = { mountid = 29, tamemessage = "voce conseguiu sua montaria" },
    ["magma crawler (mountable)"] = { mountid = 30, tamemessage = "voce conseguiu sua montaria" },
    ["dragonling (mountable)"] = { mountid = 31, tamemessage = "voce conseguiu sua montaria" },
    ["gnarlhound (mountable)"] = { mountid = 32, tamemessage = "voce conseguiu sua montaria" },
    ["water buffalo (mountable)"] = { mountid = 35, tamemessage = "voce conseguiu sua montaria" },
    ["ursagrodon (mountable)"] = { mountid = 38, tamemessage = "voce conseguiu sua montaria" },
    ["the hellgrip (mountable)"] = { mountid = 39, tamemessage = "voce conseguiu sua montaria" },
    ["noble lion (mountable)"] = { mountid = 40, tamemessage = "voce conseguiu sua montaria" },
    ["shock head (mountable)"] = { mountid = 42, tamemessage = "voce conseguiu sua montaria" },
    ["walker (mountable)"] = { mountid = 43, tamemessage = "voce conseguiu sua montaria" },
    ["flamesteed (mountable)"] = { mountid = 47, tamemessage = "voce conseguiu sua montaria" },
    ["death crawler (mountable)"] = { mountid = 46, tamemessage = "voce conseguiu sua montaria" },
    ["jade lion (mountable)"] = { mountid = 48, tamemessage = "voce conseguiu sua montaria" },
    ["jade pincer (mountable)"] = { mountid = 49, tamemessage = "voce conseguiu sua montaria" },
    ["nethersteed (mountable)"] = { mountid = 50, tamemessage = "voce conseguiu sua montaria" },
    ["tempest (mountable)"] = { mountid = 51, tamemessage = "voce conseguiu sua montaria" },
    ["winter king (mountable)"] = { mountid = 52, tamemessage = "voce conseguiu sua montaria" },
    ["doombringer (mountable)"] = { mountid = 53, tamemessage = "voce conseguiu sua montaria" },
    ["woodland prince (mountable)"] = { mountid = 54, tamemessage = "voce conseguiu sua montaria" },
    ["hailstorm fury (mountable)"] = { mountid = 55, tamemessage = "voce conseguiu sua montaria" },
    ["siegebreaker (mountable)"] = { mountid = 56, tamemessage = "voce conseguiu sua montaria" },
    ["poisonbane (mountable)"] = { mountid = 57, tamemessage = "voce conseguiu sua montaria" },
    ["blackpelt (mountable)"] = { mountid = 58, tamemessage = "voce conseguiu sua montaria" },
    ["golden dragonfly (mountable)"] = { mountid = 59, tamemessage = "voce conseguiu sua montaria" },
    ["steel bee (mountable)"] = { mountid = 60, tamemessage = "voce conseguiu sua montaria" },
    ["copper fly (mountable)"] = { mountid = 61, tamemessage = "voce conseguiu sua montaria" },
    ["tundra rambler (mountable)"] = { mountid = 62, tamemessage = "voce conseguiu sua montaria" },
    ["highland yak (mountable)"] = { mountid = 63, tamemessage = "voce conseguiu sua montaria" },
    ["glacier vagabond (mountable)"] = { mountid = 64, tamemessage = "voce conseguiu sua montaria" },
    ["flying divan (mountable)"] = { mountid = 65, tamemessage = "voce conseguiu sua montaria" },
    ["magic carpet (mountable)"] = { mountid = 66, tamemessage = "voce conseguiu sua montaria" },
    ["floating kashmir (mountable)"] = { mountid = 67, tamemessage = "voce conseguiu sua montaria" },
    ["ringtail waccoon (mountable)"] = { mountid = 68, tamemessage = "voce conseguiu sua montaria" },
    ["night waccoon (mountable)"] = { mountid = 69, tamemessage = "voce conseguiu sua montaria" },
    ["emerald waccoon (mountable)"] = { mountid = 70, tamemessage = "voce conseguiu sua montaria" },
    ["glooth glider (mountable)"] = { mountid = 71, tamemessage = "voce conseguiu sua montaria" },
    ["shadow hart (mountable)"] = { mountid = 72, tamemessage = "voce conseguiu sua montaria" },
    ["black stag (mountable)"] = { mountid = 73, tamemessage = "voce conseguiu sua montaria" },
    ["emperor deer (mountable)"] = { mountid = 74, tamemessage = "voce conseguiu sua montaria" },
    ["flitterkatzen (mountable)"] = { mountid = 75, tamemessage = "voce conseguiu sua montaria" },
    ["venompaw (mountable)"] = { mountid = 76, tamemessage = "voce conseguiu sua montaria" },
    ["batcat (mountable)"] = { mountid = 77, tamemessage = "voce conseguiu sua montaria" },
    ["sea devil (mountable)"] = { mountid = 78, tamemessage = "voce conseguiu sua montaria" },
    ["coralripper (mountable)"] = { mountid = 79, tamemessage = "voce conseguiu sua montaria" },
    ["plumfish (mountable)"] = { mountid = 80, tamemessage = "voce conseguiu sua montaria" },
    ["gorongra (mountable)"] = { mountid = 81, tamemessage = "voce conseguiu sua montaria" },
    ["noctungra (mountable)"] = { mountid = 82, tamemessage = "voce conseguiu sua montaria" },
    ["silverneck (mountable)"] = { mountid = 83, tamemessage = "voce conseguiu sua montaria" },
    ["slagsnare (mountable)"] = { mountid = 84, tamemessage = "voce conseguiu sua montaria" },
    ["nightstinger (mountable)"] = { mountid = 85, tamemessage = "voce conseguiu sua montaria" },
    ["razorcreep (mountable)"] = { mountid = 86, tamemessage = "voce conseguiu sua montaria" },
    ["nightdweller (mountable)"] = { mountid = 88, tamemessage = "voce conseguiu sua montaria" },
    ["frostflare (mountable)"] = { mountid = 89, tamemessage = "voce conseguiu sua montaria" },
    ["cinderhoof (mountable)"] = { mountid = 90, tamemessage = "voce conseguiu sua montaria" },
    ["mouldpincer (mountable)"] = { mountid = 91, tamemessage = "voce conseguiu sua montaria" },
    ["bloodcurl (mountable)"] = { mountid = 92, tamemessage = "voce conseguiu sua montaria" },
    ["leafscuttler (mountable)"] = { mountid = 93, tamemessage = "voce conseguiu sua montaria" },
    ["sparkion (mountable)"] = { mountid = 94, tamemessage = "voce conseguiu sua montaria" },
    ["swamp snapper (mountable)"] = { mountid = 95, tamemessage = "voce conseguiu sua montaria" },
    ["mould shell (mountable)"] = { mountid = 96, tamemessage = "voce conseguiu sua montaria" },
    ["reed lurker (mountable)"] = { mountid = 97, tamemessage = "voce conseguiu sua montaria" },
    ["ivory fang (mountable)"] = { mountid = 100, tamemessage = "voce conseguiu sua montaria" },
    ["shadow claw (mountable)"] = { mountid = 101, tamemessage = "voce conseguiu sua montaria" },
    ["snow pelt (mountable)"] = { mountid = 102, tamemessage = "voce conseguiu sua montaria" },
    ["jackalope (mountable)"] = { mountid = 103, tamemessage = "voce conseguiu sua montaria" },
    ["dreadhare (mountable)"] = { mountid = 104, tamemessage = "voce conseguiu sua montaria" },
    ["wolpertinger (mountable)"] = { mountid = 105, tamemessage = "voce conseguiu sua montaria" },
    ["stone rhino (mountable)"] = { mountid = 106, tamemessage = "voce conseguiu sua montaria" },
    ["gold sphinx (mountable)"] = { mountid = 107, tamemessage = "voce conseguiu sua montaria" },
    ["emerald sphinx (mountable)"] = { mountid = 108, tamemessage = "voce conseguiu sua montaria" },
    ["shadow sphinx (mountable)"] = { mountid = 109, tamemessage = "voce conseguiu sua montaria" },
    ["jungle saurian (mountable)"] = { mountid = 110, tamemessage = "voce conseguiu sua montaria" },
    ["ember saurian (mountable)"] = { mountid = 111, tamemessage = "voce conseguiu sua montaria" },
    ["lagoon saurian (mountable)"] = { mountid = 112, tamemessage = "voce conseguiu sua montaria" },
    ["blazing unicorn (mountable)"] = { mountid = 113, tamemessage = "voce conseguiu sua montaria" },
    ["arctic unicorn (mountable)"] = { mountid = 114, tamemessage = "voce conseguiu sua montaria" },
    ["prismatic unicorn (mountable)"] = { mountid = 115, tamemessage = "voce conseguiu sua montaria" },
    ["cranium spider (mountable)"] = { mountid = 116, tamemessage = "voce conseguiu sua montaria" },
    ["cave tarantula (mountable)"] = { mountid = 117, tamemessage = "voce conseguiu sua montaria" },
    ["gloom widow (mountable)"] = { mountid = 118, tamemessage = "voce conseguiu sua montaria" },
    ["mole (mountable)"] = { mountid = 119, tamemessage = "voce conseguiu sua montaria" },
    ["marsh toad (mountable)"] = { mountid = 120, tamemessage = "voce conseguiu sua montaria" },
    ["sanguine frog (mountable)"] = { mountid = 121, tamemessage = "voce conseguiu sua montaria" },
    ["toxic toad (mountable)"] = { mountid = 122, tamemessage = "voce conseguiu sua montaria" },
    ["ebony tiger (mountable)"] = { mountid = 123, tamemessage = "voce conseguiu sua montaria" },
    ["feral tiger (mountable)"] = { mountid = 124, tamemessage = "voce conseguiu sua montaria" },
    ["jungle tiger (mountable)"] = { mountid = 125, tamemessage = "voce conseguiu sua montaria" },
    ["fleeting knowledge (mountable)"] = { mountid = 126, tamemessage = "voce conseguiu sua montaria" },
    ["tawny owl (mountable)"] = { mountid = 127, tamemessage = "voce conseguiu sua montaria" },
    ["snowy owl (mountable)"] = { mountid = 128, tamemessage = "voce conseguiu sua montaria" },
    ["boreal owl (mountable)"] = { mountid = 129, tamemessage = "voce conseguiu sua montaria" },
    ["lacewing moth (mountable)"] = { mountid = 130, tamemessage = "voce conseguiu sua montaria" },
    ["hibernal moth (mountable)"] = { mountid = 131, tamemessage = "voce conseguiu sua montaria" },
    ["cold percht sleigh (mountable)"] = { mountid = 132, tamemessage = "voce conseguiu sua montaria" },
    ["bright percht sleigh (mountable)"] = { mountid = 133, tamemessage = "voce conseguiu sua montaria" },
    ["dark percht sleigh (mountable)"] = { mountid = 134, tamemessage = "voce conseguiu sua montaria" },
    ["festive snowman (mountable)"] = { mountid = 135, tamemessage = "voce conseguiu sua montaria" },
    ["muffled snowman (mountable)"] = { mountid = 136, tamemessage = "voce conseguiu sua montaria" },
    ["caped snowman (mountable)"] = { mountid = 137, tamemessage = "voce conseguiu sua montaria" },
    ["rabbit rickshaw (mountable)"] = { mountid = 138, tamemessage = "voce conseguiu sua montaria" },
    ["bunny dray (mountable)"] = { mountid = 139, tamemessage = "voce conseguiu sua montaria" },
    ["cony cart (mountable)"] = { mountid = 140, tamemessage = "voce conseguiu sua montaria" },
    ["river crocovile (mountable)"] = { mountid = 141, tamemessage = "voce conseguiu sua montaria" },
    ["swamp crocovile (mountable)"] = { mountid = 142, tamemessage = "voce conseguiu sua montaria" },
    ["nightmarish crocovile (mountable)"] = { mountid = 143, tamemessage = "voce conseguiu sua montaria" },
    ["gryphon (mountable)"] = { mountid = 144, tamemessage = "voce conseguiu sua montaria" },
    ["jousting eagle (mountable)"] = { mountid = 145, tamemessage = "voce conseguiu sua montaria" },
    ["cerberus champion (mountable)"] = { mountid = 146, tamemessage = "voce conseguiu sua montaria" },
    ["cold percht sleigh variant (mountable)"] = { mountid = 147, tamemessage = "voce conseguiu sua montaria" },
    ["bright percht sleigh variant (mountable)"] = { mountid = 148, tamemessage = "voce conseguiu sua montaria" },
    ["dark percht sleigh variant (mountable)"] = { mountid = 149, tamemessage = "voce conseguiu sua montaria" },
    ["cold percht sleigh final (mountable)"] = { mountid = 150, tamemessage = "voce conseguiu sua montaria" },
    ["bright percht sleigh final (mountable)"] = { mountid = 151, tamemessage = "voce conseguiu sua montaria" },
    ["dark percht sleigh final (mountable)"] = { mountid = 152, tamemessage = "voce conseguiu sua montaria" },
    ["battle badger (mountable)"] = { mountid = 153, tamemessage = "voce conseguiu sua montaria" },
    ["ether badger (mountable)"] = { mountid = 154, tamemessage = "voce conseguiu sua montaria" },
    ["zaoan badger (mountable)"] = { mountid = 155, tamemessage = "voce conseguiu sua montaria" },
    ["blue rolling barrel (mountable)"] = { mountid = 156, tamemessage = "voce conseguiu sua montaria" },
    ["red rolling barrel (mountable)"] = { mountid = 157, tamemessage = "voce conseguiu sua montaria" },
    ["green rolling barrel (mountable)"] = { mountid = 158, tamemessage = "voce conseguiu sua montaria" },
    ["floating sage (mountable)"] = { mountid = 159, tamemessage = "voce conseguiu sua montaria" },
    ["floating scholar (mountable)"] = { mountid = 160, tamemessage = "voce conseguiu sua montaria" },
    ["floating augur (mountable)"] = { mountid = 161, tamemessage = "voce conseguiu sua montaria" },
    ["haze (mountable)"] = { mountid = 162, tamemessage = "voce conseguiu sua montaria" },
    ["antelope (mountable)"] = { mountid = 163, tamemessage = "voce conseguiu sua montaria" },
    ["snow strider (mountable)"] = { mountid = 164, tamemessage = "voce conseguiu sua montaria" },
    ["dusk pryer (mountable)"] = { mountid = 165, tamemessage = "voce conseguiu sua montaria" },
    ["dawn strayer (mountable)"] = { mountid = 166, tamemessage = "voce conseguiu sua montaria" },
    ["phantasmal jade (mountable)"] = { mountid = 167, tamemessage = "voce conseguiu sua montaria" },
    ["savanna ostrich (mountable)"] = { mountid = 168, tamemessage = "voce conseguiu sua montaria" },
    ["coral rhea (mountable)"] = { mountid = 169, tamemessage = "voce conseguiu sua montaria" },
    ["eventide nandu (mountable)"] = { mountid = 170, tamemessage = "voce conseguiu sua montaria" },
    ["voracious hyaena (mountable)"] = { mountid = 171, tamemessage = "voce conseguiu sua montaria" },
    ["cunning hyaena (mountable)"] = { mountid = 172, tamemessage = "voce conseguiu sua montaria" },
    ["scruffy hyaena (mountable)"] = { mountid = 173, tamemessage = "voce conseguiu sua montaria" },
    ["white lion (mountable)"] = { mountid = 174, tamemessage = "voce conseguiu sua montaria" },
    ["krakoloss (mountable)"] = { mountid = 175, tamemessage = "voce conseguiu sua montaria" },
    ["merry mammoth (mountable)"] = { mountid = 176, tamemessage = "voce conseguiu sua montaria" },
    ["holiday mammoth (mountable)"] = { mountid = 177, tamemessage = "voce conseguiu sua montaria" },
    ["festive mammoth (mountable)"] = { mountid = 178, tamemessage = "voce conseguiu sua montaria" },
    ["void watcher (mountable)"] = { mountid = 179, tamemessage = "voce conseguiu sua montaria" },
    ["rune watcher (mountable)"] = { mountid = 180, tamemessage = "voce conseguiu sua montaria" },
    ["rift watcher (mountable)"] = { mountid = 181, tamemessage = "voce conseguiu sua montaria" },
    ["phant (mountable)"] = { mountid = 182, tamemessage = "voce conseguiu sua montaria" },
    ["shellodon (mountable)"] = { mountid = 183, tamemessage = "voce conseguiu sua montaria" },
    ["hyacinth (mountable)"] = { mountid = 185, tamemessage = "voce conseguiu sua montaria" },
    ["peony (mountable)"] = { mountid = 186, tamemessage = "voce conseguiu sua montaria" },
    ["dandelion (mountable)"] = { mountid = 187, tamemessage = "voce conseguiu sua montaria" },
    ["rustwurm (mountable)"] = { mountid = 188, tamemessage = "voce conseguiu sua montaria" },
    ["bogwurm (mountable)"] = { mountid = 189, tamemessage = "voce conseguiu sua montaria" },
    ["gloomwurm (mountable)"] = { mountid = 190, tamemessage = "voce conseguiu sua montaria" },
    ["emerald raven (mountable)"] = { mountid = 191, tamemessage = "voce conseguiu sua montaria" },
    ["mystic raven (mountable)"] = { mountid = 192, tamemessage = "voce conseguiu sua montaria" },
    ["radiant raven (mountable)"] = { mountid = 193, tamemessage = "voce conseguiu sua montaria" },
    ["gloothomotive (mountable)"] = { mountid = 194, tamemessage = "voce conseguiu sua montaria" },
    ["topaz shrine (mountable)"] = { mountid = 195, tamemessage = "voce conseguiu sua montaria" },
    ["jade shrine (mountable)"] = { mountid = 196, tamemessage = "voce conseguiu sua montaria" },
    ["obsidian shrine (mountable)"] = { mountid = 197, tamemessage = "voce conseguiu sua montaria" },
    ["poppy ibex (mountable)"] = { mountid = 198, tamemessage = "voce conseguiu sua montaria" },
    ["mint ibex (mountable)"] = { mountid = 199, tamemessage = "voce conseguiu sua montaria" },
    ["cinnamon ibex (mountable)"] = { mountid = 200, tamemessage = "voce conseguiu sua montaria" },
    ["giant beaver (mountable)"] = { mountid = 201, tamemessage = "voce conseguiu sua montaria" },
    ["noxious ripptor (mountable)"] = { mountid = 202, tamemessage = "voce conseguiu sua montaria" },
    ["parade horse (mountable)"] = { mountid = 203, tamemessage = "voce conseguiu sua montaria" },
    ["jousting horse (mountable)"] = { mountid = 204, tamemessage = "voce conseguiu sua montaria" },
    ["tourney horse (mountable)"] = { mountid = 205, tamemessage = "voce conseguiu sua montaria" },
    ["mutated abomination (mountable)"] = { mountid = 206, tamemessage = "voce conseguiu sua montaria" },
    ["tangerine flecked koi (mountable)"] = { mountid = 207, tamemessage = "voce conseguiu sua montaria" },
    ["brass speckled koi (mountable)"] = { mountid = 208, tamemessage = "voce conseguiu sua montaria" },
    ["ink spotted koi (mountable)"] = { mountid = 209, tamemessage = "voce conseguiu sua montaria" },
    ["frostbringer (mountable)"] = { mountid = 210, tamemessage = "voce conseguiu sua montaria" },
    ["winterstride (mountable)"] = { mountid = 211, tamemessage = "voce conseguiu sua montaria" },
    ["icebreacher (mountable)"] = { mountid = 212, tamemessage = "voce conseguiu sua montaria" },
    ["boisterous bull (mountable)"] = { mountid = 213, tamemessage = "voce conseguiu sua montaria" },
    ["surly steer (mountable)"] = { mountid = 214, tamemessage = "voce conseguiu sua montaria" },
    ["obstinate ox (mountable)"] = { mountid = 215, tamemessage = "voce conseguiu sua montaria" },
    ["darkfire devourer (mountable)"] = { mountid = 216, tamemessage = "voce conseguiu sua montaria" },
    ["spirit of purity (mountable)"] = { mountid = 217, tamemessage = "voce conseguiu sua montaria" },
    ["foxmouse (mountable)"] = { mountid = 218, tamemessage = "voce conseguiu sua montaria" },
    ["doom skull (mountable)"] = { mountid = 219, tamemessage = "voce conseguiu sua montaria" },
    ["magma skull (mountable)"] = { mountid = 220, tamemessage = "voce conseguiu sua montaria" },
    ["corpsefire skull (mountable)"] = { mountid = 221, tamemessage = "voce conseguiu sua montaria" },
    ["mystic jaguar (mountable)"] = { mountid = 222, tamemessage = "voce conseguiu sua montaria" },
    ["gorgon hydra (mountable)"] = { mountid = 223, tamemessage = "voce conseguiu sua montaria" },
    ["dawnbringer pegasus (mountable)"] = { mountid = 224, tamemessage = "voce conseguiu sua montaria" },
    ["wrathfire pegasus (mountable)"] = { mountid = 225, tamemessage = "voce conseguiu sua montaria" },
    ["skybreaker pegasus (mountable)"] = { mountid = 226, tamemessage = "voce conseguiu sua montaria" },
    ["pegasus (mountable)"] = { mountid = 227, tamemessage = "voce conseguiu sua montaria" },
    ["glacier wyrm (mountable)"] = { mountid = 228, tamemessage = "voce conseguiu sua montaria" },
    ["bog tyrant (mountable)"] = { mountid = 229, tamemessage = "voce conseguiu sua montaria" },
    ["crimson fang (mountable)"] = { mountid = 230, tamemessage = "voce conseguiu sua montaria" },
    ["bulltar mount (mountable)"] = { mountid = 231, tamemessage = "voce conseguiu sua montaria" },
    ["dargka mount (mountable)"] = { mountid = 232, tamemessage = "voce conseguiu sua montaria" },
    ["megahydra (mountable)"] = { mountid = 234, tamemessage = "voce conseguiu sua montaria" },      
    }
    
    local enhancedbox = Action()
    
    function enhancedbox.onUse(player, item, fromPosition, target, toPosition, isHotkey)
        if not target:isCreature() or not target:isMonster() or target:getMaster() then
            return false
        end
    
        local monsterConfig = config[target:getName():lower()]
        if not monsterConfig then
            return false
        end
    
        if player:hasMount(monsterConfig.mountid) then
            player:say("voce ja tem essa mount", TALKTYPE_MONSTER_SAY)
            return false
        end
    
        player:addMount(monsterConfig.mountid)
        player:say(monsterConfig.tamemessage, TALKTYPE_MONSTER_SAY)
        toPosition:sendMagicEffect(CONST_ME_SOUND_RED)
        target:remove()
    
        item:remove(1)
        return true
    end
    
    enhancedbox:id(49700)
    enhancedbox:register()
    
    
    